package calculate.interestbanking.ui;

import java.text.NumberFormat;
import java.util.Locale;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

import calculate.interestbanking.model.ibModel;

public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public ibModel model;

    public UI() {
        this.model = new ibModel();
        initComponents();
    }

    public long laiSuatKiHan() {
        long soTienDauTu = Long.parseLong(this.soTienDauTu.getText());
        float kiHanDauTu = chuyenKiHanDauTu();
        float laiSuatDauTu = Float.parseFloat(this.laiSuatDauTu.getText());
        long laiSuatDuThu = model.laiKiHan(soTienDauTu, kiHanDauTu, laiSuatDauTu);
        return laiSuatDuThu;
    }

    public long laiKepKiHan() {
        long soTienDauTu = Long.parseLong(this.soTienDauTu.getText());
        float kiHanDauTu = chuyenKiHanDauTu();
        float laiSuatDauTu = Float.parseFloat(this.laiSuatDauTu.getText());
        int chuKiLaiKep = chuyenDoiChuKi();
        long laiSuatDuThu = (long) model.laiKepKiHan(soTienDauTu, kiHanDauTu, laiSuatDauTu, chuKiLaiKep);
        return laiSuatDuThu;
    }

    public float chuyenKiHanDauTu() {
        int luaChonKiHan = this.kiHanComboBox.getSelectedIndex();
        float kiHanDauTu = Float.parseFloat(this.kyHanDauTu.getText());
        if (luaChonKiHan == 1) {
            // kì hạn đầu tư theo tháng -> bằng chính nó
            kiHanDauTu *= 1;
        } else if (luaChonKiHan == 2) {
            // kì hạn đầu tư theo năm -> số năm *12 = số tháng
            kiHanDauTu *= 12;
        }
        // else {
        // JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ dữ liệu");
        // }
        return kiHanDauTu;
    }

    public int chuyenDoiChuKi() {
        int luaChonChuKi = this.chuKiComboBox.getSelectedIndex();
        int chuKiLaiKep = 1;
        if (luaChonChuKi == 1) {
            chuKiLaiKep *= 365;
        } else if (luaChonChuKi == 2) {
            chuKiLaiKep *= 12;
        } else if (luaChonChuKi == 3) {
            chuKiLaiKep *= 4;
        } else if (luaChonChuKi == 4) {
            chuKiLaiKep *= 1;
        }
        // } else {
        // JOptionPane.showMessageDialog(null, "Vui lòng nhập đủ dữ liệu");
        // }
        return chuKiLaiKep;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        sanPhamComboBox = new javax.swing.JComboBox<>();
        soTienDauTu = new javax.swing.JTextField();
        laiSuatDauTu = new javax.swing.JTextField();
        kyHanDauTu = new javax.swing.JTextField();
        kiHanComboBox = new javax.swing.JComboBox<>();
        btnKetQua = new javax.swing.JButton();
        chuKiComboBox = new javax.swing.JComboBox<>();

        bt_TongSo = new javax.swing.JRadioButton();
        bt_LaiSuat = new javax.swing.JRadioButton();
        btn_LuaChon = new ButtonGroup();
        btn_LuaChon.add(bt_TongSo);
        btn_LuaChon.add(bt_LaiSuat);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));
        jDesktopPane1Layout.setVerticalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        jDialog1Layout.setVerticalGroup(
                jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
                jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE));
        jDialog2Layout.setVerticalGroup(
                jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 300, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel7.setBackground(new java.awt.Color(153, 153, 153));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TÍNH TOÁN SỐ TIỀN ĐẦU TƯ CÓ KỲ HẠN ");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Số tiền đầu tư(*)");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Kỳ hạn đầu tư(*)");

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Lãi suất (%/năm )(*)");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Chọn sản phẩm");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 31, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Chu kì lãi kép(*)");

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Bạn muốn(*)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 241,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 241,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 241,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(563, Short.MAX_VALUE)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 32, Short.MAX_VALUE));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE));

        sanPhamComboBox.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        sanPhamComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "", "Tiền gửi/ Tiết kiệm có kì hạn", "Tiền gửi/ Tiết kiệm theo lãi kép" }));
        sanPhamComboBox.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                sanPhamComboBoxComponentShown(evt);
            }
        });
        sanPhamComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanPhamComboBoxActionPerformed(evt);
            }
        });

        soTienDauTu.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        soTienDauTu.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }

            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {

                soTienDauTuInputMethodTextChanged(evt);
            }

        });

        laiSuatDauTu.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N

        kyHanDauTu.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        kyHanDauTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kyHanDauTuActionPerformed(evt);
            }
        });

        kiHanComboBox.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        kiHanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Tháng", "Năm" }));
        kiHanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kiHanComboBoxActionPerformed(evt);
            }
        });

        btnKetQua.setBackground(new java.awt.Color(102, 102, 102));
        btnKetQua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnKetQua.setForeground(new java.awt.Color(255, 255, 255));
        btnKetQua.setText("Kết quả");
        btnKetQua.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKetQua.setHideActionText(true);
        btnKetQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetQuaActionPerformed(evt);
            }
        });

        chuKiComboBox.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        chuKiComboBox
                .setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Ngày", "Tháng", "Quý", "Năm" }));
        chuKiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuKiComboBoxActionPerformed(evt);
            }
        });

        bt_TongSo.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        bt_TongSo.setText("Tính tổng số thu được");

        bt_LaiSuat.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        bt_LaiSuat.setText("Tính lãi suất thu được");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(sanPhamComboBox, 0, 470, Short.MAX_VALUE)
                                                        .addComponent(soTienDauTu)
                                                        .addComponent(laiSuatDauTu)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(kiHanComboBox,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(kyHanDauTu))
                                                        .addComponent(chuKiComboBox, 0,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(btnKetQua,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        442, Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(bt_TongSo,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 183,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(bt_LaiSuat,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 188,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)))
                                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(48, 48, 48)))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(sanPhamComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(soTienDauTu, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(laiSuatDauTu, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(kiHanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(kyHanDauTu, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addComponent(chuKiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(577, 577, 577))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(bt_TongSo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(bt_LaiSuat,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addComponent(btnKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap(15, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 359, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sanPhamComboBoxComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_sanPhamComboBoxComponentShown
        // TODO add your handling code here:
    }// GEN-LAST:event_sanPhamComboBoxComponentShown

    private void soTienDauTuInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {// GEN-FIRST:event_soTienDauTuInputMethodTextChanged
        // TODO add your handling code here:
        // String tienDauTu = this.soTienDauTu.getText();
        // NumberFormat numberFormat = NumberFormat.getCurrencyInstance();
        // this.soTienDauTu.setText(numberFormat.format(tienDauTu));

    }// GEN-LAST:event_soTienDauTuInputMethodTextChanged

    private void chuKiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chuKiComboBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_chuKiComboBoxActionPerformed

    // Number format
    Locale localeVN = new Locale("vi", "VN");
    NumberFormat currencyVN = NumberFormat.getCurrencyInstance(localeVN);

    // // Làm tròn số
    // NumberFormat numf = NumberFormat.getNumberInstance();
    // numf.setMinimumFractionDigits(0);
    // //Làm tròn lên
    // numf.setRoundingMode(RoundingMode.UP);

    private void btnKetQuaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnKetQuaActionPerformed
        int idSP = this.sanPhamComboBox.getSelectedIndex();
        int idKiHan = this.kiHanComboBox.getSelectedIndex();
        // SanPham sanPham = SanPham.getSanPhamByID(idSP);
        if (idSP == 0 || idKiHan == 0 || (!bt_LaiSuat.isSelected() && !bt_TongSo.isSelected())) {
            JOptionPane.showMessageDialog(this,
                    "Vui lòng nhập đủ các trường yêu cầu!");
        } else {
            if (idSP == 1) {
                long soTienDauTu = Long.parseLong(this.soTienDauTu.getText());
                long laiSuatThuDuoc = laiSuatKiHan();
                long tongSoThuDuoc = laiSuatKiHan() + soTienDauTu;
                String tongSo = currencyVN.format(tongSoThuDuoc);
                String laiSuat = currencyVN.format(laiSuatThuDuoc);
                if (bt_TongSo.isSelected()) {
                    JOptionPane.showMessageDialog(this, "Tổng số thu được: " + tongSo);
                } else if (bt_LaiSuat.isSelected()) {
                    JOptionPane.showMessageDialog(this, "Lãi suất thu được: " + laiSuat);

                }

            } else if (idSP == 2) {
                long soTienDauTu = Long.parseLong(this.soTienDauTu.getText());
                long laiSuatThuDuoc = laiKepKiHan();
                long tongSoThuDuoc = laiKepKiHan() + soTienDauTu;
                String tongSo = currencyVN.format(tongSoThuDuoc);
                String laiSuat = currencyVN.format(laiSuatThuDuoc);
                if (bt_TongSo.isSelected()) {
                    JOptionPane.showMessageDialog(this, "Tổng số thu được: " + tongSo);
                } else if (bt_LaiSuat.isSelected()) {
                    JOptionPane.showMessageDialog(this, "Lãi suất thu được: " + laiSuat);

                }
            }
        }

        // TODO add your handling code here:
    }// GEN-LAST:event_btnKetQuaActionPerformed

    private void kyHanDauTuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_kyHanDauTuActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_kyHanDauTuActionPerformed

    private void sanPhamComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sanPhamComboBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_sanPhamComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bt_LaiSuat;
    private javax.swing.JRadioButton bt_TongSo;
    private javax.swing.JButton btnKetQua;
    private javax.swing.ButtonGroup btn_LuaChon;
    private javax.swing.JComboBox<String> chuKiComboBox;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JComboBox<String> kiHanComboBox;
    private javax.swing.JTextField kyHanDauTu;
    private javax.swing.JTextField laiSuatDauTu;
    private javax.swing.JComboBox<String> sanPhamComboBox;
    private javax.swing.JTextField soTienDauTu;
    // End of variables declaration//GEN-END:variables
}
